import { cn } from "@/lib/utils";
import "./globals.css";
import { inter } from "@/lib/fonts";

export const metadata = {
  title: {
    default: "Department of Streetware Supplies",
    template: "%s | DOSS",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "antialiased")}>{children}</body>
    </html>
  );
}
