import { cn } from "@/lib/utils";
import "./globals.css";
import { inter } from "@/lib/fonts";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: {
    default: "Department of Streetware Supplies",
    template: "%s | DOSS",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(inter.className, "antialiased")}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
